name: tlvg-gs
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py310hc06175d_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py310h06a4308_0
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - chardet=4.0.0=py310h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - cmake=3.26.4=h96355d8_0
  - conda=23.5.2=py310h06a4308_0
  - conda-build=24.3.0=py310h06a4308_0
  - conda-content-trust=0.2.0=py310h06a4308_0
  - conda-index=0.4.0=pyhd3eb1b0_0
  - conda-libmamba-solver=23.7.0=py310h06a4308_0
  - conda-package-handling=2.2.0=py310h06a4308_0
  - conda-package-streaming=0.9.0=py310h06a4308_0
  - cryptography=42.0.5=py310hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distro=1.8.0=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.20.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=py310h06a4308_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.19.2=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libarchive=3.6.2=h6ac8c49_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblief=0.12.3=h6a678d5_0
  - libmamba=1.5.8=hfe524e5_1
  - libmambapy=1.5.8=py310h2dafd23_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsolv=0.7.24=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - menuinst=2.0.2=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - more-itertools=10.1.0=py310h06a4308_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=23.3.1=py310h06a4308_0
  - pkginfo=1.9.6=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py310h6a678d5_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyopenssl=24.0.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - pytorch=2.3.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py310h06a4308_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py310h06a4308_1
  - rhash=1.4.3=hdbd6064_0
  - rpds-py=0.10.6=py310hb02cf49_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - torchaudio=2.3.0=py310_cu118
  - torchtriton=2.3.0=py310
  - torchvision=0.18.0=py310_cu118
  - traitlets=5.7.1=py310h06a4308_0
  - truststore=0.8.0=py310h06a4308_0
  - typing_extensions=4.9.0=py310h06a4308_1
  - urllib3=2.1.0=py310h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - blinker==1.9.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - dash==3.0.0
      - defusedxml==0.7.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - executing==2.2.0
      - expecttest==0.2.1
      - fastapi==0.115.11
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - flask==3.0.3
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==3.50.2
      - gradio-client==0.6.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.23.5
      - hypothesis==6.100.1
      - icecream==2.1.4
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lark==1.1.9
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - multidict==6.2.0
      - narwhals==1.31.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nvidia-ml-py==12.570.86
      - nvitop==1.4.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - optree==0.11.0
      - orjson==3.10.15
      - pandas==2.2.3
      - pillow==9.4.0
      - plotly==6.0.1
      - plyfile==1.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==5.29.4
      - pycocotools==2.0.8
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - pyperclip==1.9.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-etcd==0.4.5
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.1
      - regex==2024.11.6
      - retrying==1.3.4
      - rich==13.9.4
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentry-sdk==2.24.0
      - setproctitle==1.3.5
      - simple-parsing==0.1.7
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - starlette==0.46.1
      - stringcase==1.2.0
      - supervision==0.25.1
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tiktoken==0.7.0
      - timm==1.0.15
      - tokenizers==0.20.3
      - torchelastic==0.2.2
      - torchmetrics==1.7.0
      - tqdm==4.67.1
      - transformers==4.46.3
      - types-dataclasses==0.6.6
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uvicorn==0.34.0
      - wandb==0.19.8
      - websockets==11.0.3
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0